- name: Provision Infrastructure
  hosts: web
  become: yes
  roles:
    - web_server
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_DEFAULT_REGION: "{{ region }}"
