php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]
mysql_root_password: "password123"
mysql_db: "wordpress"
mysql_user: "admin"
mysql_password: "password123"
global_rds_info_host: mydb.chcegce0exds.ap-southeast-1.rds.amazonaws.com
