- name: Create RDS Security Group
  ec2_group:
    name: rds-sg
    description: RDS Security Group
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: 0.0.0.0/0
  register: rds_sg

- name: Create RDS Instance
  rds_instance:
    db_instance_identifier: mydb
    engine: mysql
    db_instance_class: db.t3.micro
    allocated_storage: 20
    master_username: "{{ master_username }}"
    master_user_password: "{{ master_user_password }}"
    db_name: "{{ db_name }}" 
    publicly_accessible: true
    region: "{{ region }}"
    vpc_security_group_ids:
      - "{{ rds_sg.group_id }}"
  register: rds_info

